zalando-zmon/zmon-aws-agent

zmon-agent.py
=> Work around ELB describe_tags limit

requirements.txt, zmon-agent.py
Retrying from scratch after rebase on newer master.
=> Assign properties from Tags automatically

zmon_aws_agent/main.py
=> Fix new_entities check bug

zmon_aws_agent/main.py
=> Fix entity dict comparison

zmon_aws_agent/aws.py
=> #37 replace invalid chars in entity ID with dash

zmon_aws_agent/aws.py
=> Fix record key Type

.travis.yml, README.rst, setup.py
+ Run tests
+ Coverage report - codecov.io
+ Add badges
Fix #5
=> Run tests with coverage + add badges

tests/conftest.py, tests/test_aws.py, zmon_aws_agent/aws.py, zmon_aws_agent/main.py
- Sync IAM certificates
- Sync ACM certificates
Note: In case of ACM certificates with `Status` not `ISSUED`, expiration date is not available, so I set it to '' (not sure if this is the desired behavior in this case)
Resolve #53
=> Add support for IAM/ACM certificates

README.rst
Update README to match updated aws entities.
=> Update README to match updated aws entities

tests/conftest.py, zmon_aws_agent/aws.py
=> Add new field for docker image

Dockerfile
=> Update python base image

zmon_aws_agent/aws.py
When a new AutoScaling Group is created (or when a stack is deleted),
for a short period of time it doesn't have any instances.  Then the
agent tries to call describe_instances w/o the list of instance ids,
which returns the list of *all* account instances.
Fix this by not describing instances, then the ASG's list is empty.
=> Don't describe ASG instances when there are none

tests/conftest.py, zmon_aws_agent/aws.py
=> Instance name as entity

.travis.yml, tox.ini
Fix codecov reporting with Tox
=> Fix codecov reporting

zmon_aws_agent/aws.py
Needed for EBS credit monitoring
=> Added EBS volumes to Instances

zmon_aws_agent/aws.py
=> Fix ebs data being added to right dict

zmon_aws_agent/aws.py, zmon_aws_agent/common.py, zmon_aws_agent/main.py
=> Improve api exception handling

tests/conftest.py, tests/test_aws.py, zmon_aws_agent/aws.py, zmon_aws_agent/main.py
+ Add instance type, storage type and storage size
+ Sync only every 15 mins
=> Add instance info to RDS database

Dockerfile, tests/conftest.py, tests/test_aws.py, zmon_aws_agent/aws.py
* add image_id, image_name and image_date every 15 minutes to the instance entity
* use latest python image to satisfy depencency for setuptools
=> Image in instance entities

tests/conftest.py, tests/test_aws.py, zmon_aws_agent/aws.py
also: fix dateformat so it's parseable by zmon's time() helper function
=> schedule to run at 21:*

tests/conftest.py, tests/test_aws.py, zmon_aws_agent/aws.py
empty list means all images -> full CPU for ages...
=> do not fetch images with empty list

requirements.txt, zmon_aws_agent/aws.py, zmon_aws_agent/main.py, zmon_aws_agent/postgresql.py
otherwise we produce flapping alerts like
```
2017-11-02 04:08:01     ALERT_ENTITY_STARTED
"entity-name-H4Sh01[aws:1234567890:eu-central-1]"
{"td":3.89E-4,"worker":"plocal.ip-172-31-132-123","ts":1.50959207725566E9,"value":[{"Code":"instance-stop","Description":"The instance is running on degraded
hardware","NotBefore":"2017-11-14T22:00:00+00:00"}]}
2017-11-02 04:18:00     ALERT_ENTITY_ENDED
"entity-name-H4Sh01[aws:1234567890:eu-central-1]"
{"td":6.02E-4,"worker":"plocal.ip-172-31-132-123","ts":1.509592677890665E9,"value":[]}
2017-11-02 08:06:59     ALERT_ENTITY_STARTED
"entity-name-H4Sh01[aws:1234567890:eu-central-1]"
{"td":4.84E-4,"worker":"plocal.ip-172-31-140-110","ts":1.509606418656158E9,"value":[{"Code":"instance-stop","Description":"The instance is running on degraded …
```
=> copy events from existing instance

tests/test_aws.py, zmon_aws_agent/aws.py, zmon_aws_agent/main.py
updated test not to return the default limit in non failure case also
... fixed #124
=> use previous known limit if call failed

Dockerfile, README.rst, delivery.yaml, requirements.txt, setup.py, start.sh, tests/conftest.py, tests/test_postgresql.py, tox.ini, zmon_aws_agent/aws.py, zmon_aws_agent/common.py, zmon_aws_agent/main.py, zmon_aws_agent/postgresql.py
similar to https://github.com/zalando-zmon/zmon-worker/pull/317
needs same fix when opentracing_utils is done
=> opentracing support

delivery.yaml
=> fix [: !=: unary operator expected

zmon_aws_agent/postgresql.py
=> fix list_postgresql_databases

zmon_aws_agent/postgresql.py
Fix key error in AWS agent postgresql discovery.
=> Fix key error in AWS agent postgresql discovery.

tests/conftest.py, zmon_aws_agent/aws.py
then we can filter for those...
=> let certificates "in_use" be a string

requirements.txt
to latest to fix a bug in there
=> bump cli version

zmon_aws_agent/main.py
so we can override the default zmon_cli timeout
=> explicity set timeout

start.sh
to prevent agents stucking problem
=> set timeout for agent execution

tests/conftest.py, zmon_aws_agent/aws.py
Also added validation status for ACM issues certificates.
=> Fixed the validation method for ACM certs

tests/conftest.py, zmon_aws_agent/aws.py
I somehow forgot to add the name which is the only human-readable piece of information. :(
=> servicequota: add quota name to the entity

tests/conftest.py, zmon_aws_agent/aws.py
=> instance: add availability_zone field
